name: sos_guardian
description: SOS Guardian - Emergency Alert System
publish_to: none
version: 3.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # State & storage
  provider: ^6.1.2
  shared_preferences: ^2.3.1
  uuid: ^4.4.2
  intl: ^0.19.0

  # Network
  http: ^1.2.1

  # Location
  geolocator: ^12.0.0

  # Notifications  (NO background service - this was the OOM crash cause)
  flutter_local_notifications: ^17.1.2

  # Permissions
  permission_handler: ^11.3.1

  # SMS (launches phone's SMS app)
  url_launcher: ^6.3.0

  # Crash detection
  sensors_plus: ^4.0.1

  # BLE relay
  flutter_blue_plus: ^1.36.8

  record: 5.1.0
  path_provider: ^2.1.4
  http_parser: ^4.0.1

dependency_overrides:
  record_linux: 0.7.2
  record_platform_interface: 1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
